-- Melhoria: historico administrativo.
-- Rode este SQL uma vez no Supabase SQL Editor.
-- Objetivo: registrar as principais acoes do painel do administrador
-- para facilitar suporte, auditoria e acompanhamento de clientes.

create schema if not exists extensions;
set search_path = public, extensions;

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  actor_email text,
  action_type text not null,
  target_email text,
  target_name text,
  details text,
  created_at timestamptz not null default now()
);

alter table public.admin_audit_logs enable row level security;

create index if not exists idx_admin_audit_logs_created_at
  on public.admin_audit_logs (created_at desc);

create index if not exists idx_admin_audit_logs_target_email
  on public.admin_audit_logs (target_email);

create or replace function public.admin_register_audit(
  action_type text,
  target_email text default null,
  target_name text default null,
  action_details text default null
)
returns bigint
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  normalized_target_email text;
  actor_email_value text;
  new_log_id bigint;
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Somente administradores podem registrar historico.';
  end if;

  normalized_target_email := nullif(lower(trim(coalesce(target_email, ''))), '');

  select lower(u.email)
    into actor_email_value
  from auth.users u
  where u.id = auth.uid()
  limit 1;

  insert into public.admin_audit_logs (
    actor_id,
    actor_email,
    action_type,
    target_email,
    target_name,
    details,
    created_at
  )
  values (
    auth.uid(),
    actor_email_value,
    left(trim(coalesce(action_type, 'acao_admin')), 60),
    normalized_target_email,
    nullif(left(trim(coalesce(target_name, '')), 120), ''),
    nullif(left(trim(coalesce(action_details, '')), 300), ''),
    now()
  )
  returning id into new_log_id;

  return new_log_id;
end;
$$;

create or replace function public.admin_list_audit_logs(max_rows integer default 20)
returns table (
  id bigint,
  action_type text,
  target_email text,
  target_name text,
  details text,
  actor_email text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public, extensions
stable
as $$
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Somente administradores podem consultar historico.';
  end if;

  return query
  select
    l.id,
    l.action_type,
    l.target_email,
    l.target_name,
    l.details,
    l.actor_email,
    l.created_at
  from public.admin_audit_logs l
  order by l.created_at desc
  limit greatest(1, least(coalesce(max_rows, 20), 100));
end;
$$;

revoke all on table public.admin_audit_logs from anon, authenticated;
revoke all on function public.admin_register_audit(text, text, text, text) from public;
revoke all on function public.admin_list_audit_logs(integer) from public;

grant execute on function public.admin_register_audit(text, text, text, text) to authenticated;
grant execute on function public.admin_list_audit_logs(integer) to authenticated;
