-- SQL unico de producao - Prioridade 1: Confiabilidade.
-- Objetivo: consolidar estrutura, indices, RLS e RPCs usadas pelo app.
-- Rode no SQL Editor do Supabase depois de fazer backup.
-- Este script nao apaga clientes nem estados financeiros.

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;
set search_path = public, extensions;

create table if not exists public.user_states (
  user_id uuid primary key references auth.users(id) on delete cascade,
  app_state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.allowed_emails (
  email text primary key,
  full_name text,
  role text not null default 'user',
  status text not null default 'active',
  valid_until date,
  valid_until_at timestamptz,
  temp_password text,
  temp_password_hash text,
  must_change_password boolean not null default true,
  is_trial boolean not null default false,
  plan_type text not null default 'manual',
  purchase_platform text,
  purchase_reference text,
  subscription_started_at timestamptz,
  subscription_updated_at timestamptz,
  account_created_at timestamptz,
  claimed_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.app_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  full_name text,
  role text not null default 'user',
  status text not null default 'active',
  valid_until date,
  valid_until_at timestamptz,
  is_trial boolean not null default false,
  plan_type text not null default 'manual',
  purchase_platform text,
  purchase_reference text,
  subscription_started_at timestamptz,
  subscription_updated_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_login_at timestamptz
);

create table if not exists public.access_deletion_notices (
  email text primary key,
  reason text not null,
  deleted_by uuid references auth.users(id) on delete set null,
  deleted_at timestamptz not null default now()
);

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  actor_email text,
  action_type text not null,
  target_email text,
  target_name text,
  details text,
  created_at timestamptz not null default now()
);

alter table public.allowed_emails
  add column if not exists valid_until_at timestamptz,
  add column if not exists temp_password_hash text,
  add column if not exists must_change_password boolean not null default true,
  add column if not exists is_trial boolean not null default false,
  add column if not exists plan_type text not null default 'manual',
  add column if not exists purchase_platform text,
  add column if not exists purchase_reference text,
  add column if not exists subscription_started_at timestamptz,
  add column if not exists subscription_updated_at timestamptz,
  add column if not exists account_created_at timestamptz,
  add column if not exists claimed_at timestamptz,
  add column if not exists created_by uuid references auth.users(id) on delete set null,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table public.app_profiles
  add column if not exists valid_until_at timestamptz,
  add column if not exists is_trial boolean not null default false,
  add column if not exists plan_type text not null default 'manual',
  add column if not exists purchase_platform text,
  add column if not exists purchase_reference text,
  add column if not exists subscription_started_at timestamptz,
  add column if not exists subscription_updated_at timestamptz,
  add column if not exists created_by uuid references auth.users(id) on delete set null,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists last_login_at timestamptz;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'allowed_emails_role_check'
  ) then
    alter table public.allowed_emails
      add constraint allowed_emails_role_check check (role in ('admin', 'user'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'allowed_emails_status_check'
  ) then
    alter table public.allowed_emails
      add constraint allowed_emails_status_check check (status in ('active', 'blocked'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'allowed_emails_plan_type_check'
  ) then
    alter table public.allowed_emails
      add constraint allowed_emails_plan_type_check check (plan_type in ('manual', 'trial', 'monthly', 'semiannual', 'annual'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'app_profiles_role_check'
  ) then
    alter table public.app_profiles
      add constraint app_profiles_role_check check (role in ('admin', 'user'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'app_profiles_status_check'
  ) then
    alter table public.app_profiles
      add constraint app_profiles_status_check check (status in ('active', 'blocked'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'app_profiles_plan_type_check'
  ) then
    alter table public.app_profiles
      add constraint app_profiles_plan_type_check check (plan_type in ('manual', 'trial', 'monthly', 'semiannual', 'annual'));
  end if;
end $$;

update public.allowed_emails
set email = lower(trim(email))
where email <> lower(trim(email));

update public.app_profiles
set email = lower(trim(email))
where email <> lower(trim(email));

update public.allowed_emails
set valid_until_at = ((valid_until::text || ' 23:59:59')::timestamp at time zone 'America/Sao_Paulo')
where valid_until_at is null
  and valid_until is not null;

update public.app_profiles
set valid_until_at = ((valid_until::text || ' 23:59:59')::timestamp at time zone 'America/Sao_Paulo')
where valid_until_at is null
  and valid_until is not null;

update public.allowed_emails
set plan_type = case
  when is_trial then 'trial'
  when plan_type is null or plan_type = '' then 'manual'
  else plan_type
end;

update public.app_profiles
set plan_type = case
  when is_trial then 'trial'
  when plan_type is null or plan_type = '' then 'manual'
  else plan_type
end;

update public.allowed_emails
set temp_password_hash = crypt(temp_password, gen_salt('bf')),
    temp_password = null,
    updated_at = now()
where coalesce(temp_password, '') <> ''
  and temp_password_hash is null;

create sequence if not exists public.trial_account_number_seq
  as bigint
  start with 1
  increment by 1;

create index if not exists allowed_emails_status_validity_idx on public.allowed_emails (status, valid_until_at);
create index if not exists allowed_emails_role_status_idx on public.allowed_emails (role, status);
create index if not exists allowed_emails_plan_idx on public.allowed_emails (plan_type);
create index if not exists allowed_emails_created_at_idx on public.allowed_emails (created_at desc);
create index if not exists allowed_emails_updated_at_idx on public.allowed_emails (updated_at desc);
create index if not exists app_profiles_email_idx on public.app_profiles (email);
create index if not exists app_profiles_status_validity_idx on public.app_profiles (status, valid_until_at);
create index if not exists app_profiles_plan_idx on public.app_profiles (plan_type);
create index if not exists app_profiles_created_at_idx on public.app_profiles (created_at desc);
create index if not exists app_profiles_last_login_idx on public.app_profiles (last_login_at desc);
create index if not exists user_states_updated_at_idx on public.user_states (updated_at desc);
create index if not exists access_deletion_notices_deleted_at_idx on public.access_deletion_notices (deleted_at desc);
create index if not exists admin_audit_logs_created_at_idx on public.admin_audit_logs (created_at desc);
create index if not exists admin_audit_logs_target_email_idx on public.admin_audit_logs (target_email);

alter table public.user_states enable row level security;
alter table public.allowed_emails enable row level security;
alter table public.app_profiles enable row level security;
alter table public.access_deletion_notices enable row level security;
alter table public.admin_audit_logs enable row level security;
alter table public.user_states force row level security;
alter table public.allowed_emails force row level security;
alter table public.app_profiles force row level security;

revoke all on table public.user_states from anon, authenticated;
revoke all on table public.allowed_emails from anon, authenticated;
revoke all on table public.app_profiles from anon, authenticated;
revoke all on table public.access_deletion_notices from anon, authenticated;
revoke all on table public.admin_audit_logs from anon, authenticated;
grant select, insert, update, delete on table public.user_states to authenticated;
grant select, insert, update, delete on table public.allowed_emails to authenticated;
grant select, insert, update, delete on table public.app_profiles to authenticated;
grant select, insert, update, delete on table public.access_deletion_notices to authenticated;
grant select, insert on table public.admin_audit_logs to authenticated;

drop function if exists public.admin_create_managed_access(text, text, text, text, timestamptz, text, text, text);
drop function if exists public.admin_create_trial_access(text, text, integer);
drop function if exists public.admin_list_accesses();
drop function if exists public.admin_apply_access_plan(text, text, text, text);
drop function if exists public.get_my_access_status();
drop function if exists public.can_start_first_access(text, text);
drop function if exists public.mark_password_changed();
drop function if exists public.next_trial_email();
drop function if exists public.admin_set_auth_ban(text, boolean);
drop function if exists public.admin_delete_access_account(text);
drop function if exists public.admin_delete_access_account(text, text);
drop function if exists public.get_access_deletion_notice(text);
drop trigger if exists trg_clear_access_deletion_notice_on_allow on public.allowed_emails;
drop function if exists public.clear_access_deletion_notice_on_allow();
drop function if exists public.admin_register_audit(text, text, text, text);
drop function if exists public.admin_list_audit_logs(integer);

create or replace function public.normalize_plan_type(selected_plan text)
returns text
language sql
stable
as $$
  select case lower(trim(coalesce(selected_plan, 'monthly')))
    when 'trial' then 'trial'
    when 'monthly' then 'monthly'
    when 'semiannual' then 'semiannual'
    when 'annual' then 'annual'
    when 'manual' then 'manual'
    else 'monthly'
  end;
$$;

create or replace function public.get_plan_expiry(base_date timestamptz, selected_plan text)
returns timestamptz
language sql
stable
as $$
  select case public.normalize_plan_type(selected_plan)
    when 'trial' then base_date + interval '30 minutes'
    when 'monthly' then base_date + interval '30 days'
    when 'semiannual' then base_date + interval '6 months'
    when 'annual' then base_date + interval '12 months'
    else base_date + interval '30 days'
  end;
$$;

create or replace function public.is_admin(uid uuid)
returns boolean
language sql
security definer
set search_path = public, extensions
stable
as $$
  select uid is not null
    and (
      exists (
        select 1
        from auth.users u
        join public.allowed_emails a on a.email = lower(u.email)
        where u.id = uid
          and a.role = 'admin'
          and a.status = 'active'
          and (
            (a.valid_until_at is not null and a.valid_until_at >= now())
            or (a.valid_until_at is null and (a.valid_until is null or a.valid_until >= current_date))
          )
      )
      or exists (
        select 1
        from public.app_profiles p
        where p.user_id = uid
          and p.role = 'admin'
          and p.status = 'active'
          and (
            (p.valid_until_at is not null and p.valid_until_at >= now())
            or (p.valid_until_at is null and (p.valid_until is null or p.valid_until >= current_date))
          )
      )
    );
$$;

create or replace function public.has_active_access(user_email text)
returns boolean
language sql
security definer
set search_path = public, extensions
stable
as $$
  select exists (
    select 1
    from public.allowed_emails a
    where a.email = lower(trim(coalesce(user_email, '')))
      and a.status = 'active'
      and (
        (a.valid_until_at is not null and a.valid_until_at >= now())
        or (a.valid_until_at is null and (a.valid_until is null or a.valid_until >= current_date))
      )
  );
$$;

create or replace function public.has_any_admin()
returns boolean
language sql
security definer
set search_path = public, extensions
stable
as $$
  select exists (
    select 1
    from public.allowed_emails a
    where a.role = 'admin'
      and a.status = 'active'
  );
$$;

create or replace function public.get_access_deletion_notice(user_email text)
returns table (
  email text,
  reason text,
  deleted_at timestamptz
)
language plpgsql
security definer
set search_path = public, extensions
stable
as $$
declare
  normalized_email text;
begin
  normalized_email := lower(trim(coalesce(user_email, '')));

  if normalized_email = '' then
    return;
  end if;

  return query
  select n.email, n.reason, n.deleted_at
    from public.access_deletion_notices n
   where n.email = normalized_email
   limit 1;
end;
$$;

create or replace function public.admin_register_audit(
  action_type text,
  target_email text default null,
  target_name text default null,
  action_details text default null
)
returns bigint
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  normalized_target_email text;
  actor_email_value text;
  new_log_id bigint;
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Somente administradores podem registrar historico.';
  end if;

  normalized_target_email := nullif(lower(trim(coalesce(target_email, ''))), '');

  select lower(u.email)
    into actor_email_value
  from auth.users u
  where u.id = auth.uid()
  limit 1;

  insert into public.admin_audit_logs (
    actor_id,
    actor_email,
    action_type,
    target_email,
    target_name,
    details,
    created_at
  )
  values (
    auth.uid(),
    actor_email_value,
    left(trim(coalesce(action_type, 'acao_admin')), 60),
    normalized_target_email,
    nullif(left(trim(coalesce(target_name, '')), 120), ''),
    nullif(left(trim(coalesce(action_details, '')), 300), ''),
    now()
  )
  returning id into new_log_id;

  return new_log_id;
end;
$$;

create or replace function public.admin_list_audit_logs(max_rows integer default 20)
returns table (
  id bigint,
  action_type text,
  target_email text,
  target_name text,
  details text,
  actor_email text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public, extensions
stable
as $$
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Somente administradores podem consultar historico.';
  end if;

  return query
  select
    l.id,
    l.action_type,
    l.target_email,
    l.target_name,
    l.details,
    l.actor_email,
    l.created_at
  from public.admin_audit_logs l
  order by l.created_at desc
  limit greatest(1, least(coalesce(max_rows, 20), 100));
end;
$$;

create or replace function public.hash_allowed_email_temp_password()
returns trigger
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  new.email := lower(trim(new.email));

  if coalesce(new.temp_password, '') <> '' then
    new.temp_password_hash := crypt(new.temp_password, gen_salt('bf'));
    new.temp_password := null;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_hash_allowed_email_temp_password on public.allowed_emails;
create trigger trg_hash_allowed_email_temp_password
before insert or update of email, temp_password on public.allowed_emails
for each row
execute function public.hash_allowed_email_temp_password();

create or replace function public.can_start_first_access(user_email text, temp_password_value text)
returns table (
  email text,
  full_name text,
  role text,
  status text,
  valid_until date,
  valid_until_at timestamptz,
  must_change_password boolean,
  is_trial boolean,
  plan_type text,
  effective_status text
)
language plpgsql
security definer
set search_path = public, extensions
stable
as $$
declare
  normalized_email text;
begin
  normalized_email := lower(trim(coalesce(user_email, '')));

  if normalized_email = '' or coalesce(temp_password_value, '') = '' then
    return;
  end if;

  return query
  select
    a.email,
    a.full_name,
    coalesce(a.role, 'user') as role,
    coalesce(a.status, 'blocked') as status,
    a.valid_until,
    a.valid_until_at,
    coalesce(a.must_change_password, false) as must_change_password,
    coalesce(a.is_trial, false) as is_trial,
    coalesce(a.plan_type, 'manual') as plan_type,
    case
      when a.status = 'blocked' then 'blocked'
      when a.valid_until_at is not null and a.valid_until_at < now() then 'expired'
      when a.valid_until_at is null and a.valid_until is not null and a.valid_until < current_date then 'expired'
      else 'active'
    end as effective_status
  from public.allowed_emails a
  where a.email = normalized_email
    and (
      (a.temp_password_hash is not null and a.temp_password_hash = crypt(temp_password_value, a.temp_password_hash))
      or (a.temp_password_hash is null and coalesce(a.temp_password, '') = temp_password_value)
    )
    and a.status = 'active'
    and (
      (a.valid_until_at is not null and a.valid_until_at >= now())
      or (a.valid_until_at is null and (a.valid_until is null or a.valid_until >= current_date))
    )
  limit 1;
end;
$$;

create or replace function public.get_my_access_status()
returns table (
  email text,
  full_name text,
  role text,
  status text,
  valid_until date,
  valid_until_at timestamptz,
  temp_password text,
  must_change_password boolean,
  is_trial boolean,
  plan_type text,
  purchase_platform text,
  purchase_reference text,
  subscription_started_at timestamptz,
  subscription_updated_at timestamptz,
  account_created_at timestamptz,
  claimed_at timestamptz,
  effective_status text
)
language plpgsql
security definer
set search_path = public, extensions
stable
as $$
declare
  current_email text;
begin
  current_email := lower(coalesce(auth.jwt() ->> 'email', ''));

  if current_email = '' then
    return query
    select
      null::text,
      null::text,
      null::text,
      null::text,
      null::date,
      null::timestamptz,
      null::text,
      false,
      false,
      'manual'::text,
      null::text,
      null::text,
      null::timestamptz,
      null::timestamptz,
      null::timestamptz,
      null::timestamptz,
      'missing'::text;
    return;
  end if;

  return query
  select
    coalesce(a.email, current_email) as email,
    a.full_name,
    coalesce(a.role, 'user') as role,
    coalesce(a.status, 'blocked') as status,
    a.valid_until,
    a.valid_until_at,
    null::text as temp_password,
    coalesce(a.must_change_password, false) as must_change_password,
    coalesce(a.is_trial, false) as is_trial,
    coalesce(a.plan_type, 'manual') as plan_type,
    a.purchase_platform,
    a.purchase_reference,
    a.subscription_started_at,
    a.subscription_updated_at,
    a.account_created_at,
    a.claimed_at,
    case
      when a.email is null then 'missing'
      when a.status = 'blocked' then 'blocked'
      when a.valid_until_at is not null and a.valid_until_at < now() then 'expired'
      when a.valid_until_at is null and a.valid_until is not null and a.valid_until < current_date then 'expired'
      else 'active'
    end as effective_status
  from (select current_email as current_email_value) e
  left join public.allowed_emails a on a.email = e.current_email_value;
end;
$$;

create or replace function public.next_trial_email()
returns text
language plpgsql
security definer
set search_path = public, extensions
volatile
as $$
declare
  next_number bigint;
  candidate_email text;
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Somente administradores podem gerar perfil teste.';
  end if;

  loop
    next_number := nextval('public.trial_account_number_seq'::regclass);
    candidate_email := lower('teste' || lpad(next_number::text, 3, '0') || '@trial.controlefinanceiro.app');

    exit when not exists (select 1 from public.allowed_emails a where a.email = candidate_email)
      and not exists (select 1 from public.app_profiles p where lower(p.email) = candidate_email)
      and not exists (select 1 from auth.users u where lower(u.email) = candidate_email);
  end loop;

  return candidate_email;
end;
$$;

create or replace function public.admin_create_managed_access(
  target_email text,
  target_full_name text,
  target_role text,
  selected_plan text,
  selected_valid_until_at timestamptz,
  temp_password_value text,
  selected_platform text default 'manual',
  selected_reference text default null
)
returns table (
  email text,
  full_name text,
  role text,
  status text,
  plan_type text,
  valid_until date,
  valid_until_at timestamptz,
  is_trial boolean,
  must_change_password boolean
)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  normalized_email text;
  normalized_role text;
  normalized_plan text;
  expires_at timestamptz;
  cleaned_name text;
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Sua sessao nao tem permissao de administrador ativa no Supabase.';
  end if;

  normalized_email := lower(trim(coalesce(target_email, '')));
  normalized_role := lower(trim(coalesce(target_role, 'user')));
  normalized_plan := public.normalize_plan_type(selected_plan);
  expires_at := coalesce(selected_valid_until_at, public.get_plan_expiry(now(), normalized_plan));
  cleaned_name := nullif(trim(coalesce(target_full_name, '')), '');

  if normalized_email = '' or normalized_email !~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$' then
    raise exception 'Informe um e-mail valido.';
  end if;

  if normalized_role not in ('admin', 'user') then
    raise exception 'Tipo de conta invalido.';
  end if;

  if coalesce(temp_password_value, '') = '' then
    raise exception 'Senha temporaria invalida.';
  end if;

  insert into public.allowed_emails (
    email,
    full_name,
    role,
    status,
    valid_until,
    valid_until_at,
    temp_password,
    temp_password_hash,
    must_change_password,
    is_trial,
    plan_type,
    purchase_platform,
    purchase_reference,
    subscription_started_at,
    subscription_updated_at,
    account_created_at,
    claimed_at,
    created_by,
    updated_at
  )
  values (
    normalized_email,
    cleaned_name,
    normalized_role,
    'active',
    expires_at::date,
    expires_at,
    null,
    crypt(temp_password_value, gen_salt('bf')),
    true,
    false,
    normalized_plan,
    coalesce(nullif(trim(coalesce(selected_platform, '')), ''), 'manual'),
    nullif(trim(coalesce(selected_reference, '')), ''),
    now(),
    now(),
    null,
    null,
    auth.uid(),
    now()
  )
  on conflict on constraint allowed_emails_pkey do update
     set full_name = coalesce(excluded.full_name, public.allowed_emails.full_name),
         role = excluded.role,
         status = 'active',
         valid_until = excluded.valid_until,
         valid_until_at = excluded.valid_until_at,
         temp_password = null,
         temp_password_hash = excluded.temp_password_hash,
         must_change_password = true,
         is_trial = false,
         plan_type = excluded.plan_type,
         purchase_platform = excluded.purchase_platform,
         purchase_reference = excluded.purchase_reference,
         subscription_started_at = coalesce(public.allowed_emails.subscription_started_at, now()),
         subscription_updated_at = now(),
         updated_at = now();

  update public.app_profiles p
     set full_name = coalesce(cleaned_name, p.full_name),
         role = normalized_role,
         status = 'active',
         valid_until = expires_at::date,
         valid_until_at = expires_at,
         is_trial = false,
         plan_type = normalized_plan,
         purchase_platform = coalesce(nullif(trim(coalesce(selected_platform, '')), ''), p.purchase_platform),
         purchase_reference = nullif(trim(coalesce(selected_reference, '')), ''),
         subscription_started_at = coalesce(p.subscription_started_at, now()),
         subscription_updated_at = now(),
         updated_at = now()
   where lower(p.email) = normalized_email;

  return query
  select
    a.email,
    a.full_name,
    a.role,
    a.status,
    coalesce(a.plan_type, 'manual') as plan_type,
    a.valid_until,
    a.valid_until_at,
    coalesce(a.is_trial, false) as is_trial,
    coalesce(a.must_change_password, false) as must_change_password
  from public.allowed_emails a
  where a.email = normalized_email;
end;
$$;

create or replace function public.admin_create_trial_access(
  target_full_name text,
  temp_password_value text,
  trial_minutes integer default 30
)
returns table (
  email text,
  full_name text,
  role text,
  status text,
  plan_type text,
  valid_until date,
  valid_until_at timestamptz,
  is_trial boolean,
  temp_password text
)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  next_number bigint;
  candidate_email text;
  expires_at timestamptz;
  cleaned_name text;
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Sua sessao nao tem permissao de administrador ativa no Supabase.';
  end if;

  if coalesce(temp_password_value, '') = '' then
    raise exception 'Senha temporaria invalida.';
  end if;

  cleaned_name := coalesce(nullif(trim(coalesce(target_full_name, '')), ''), 'Perfil Teste');

  loop
    next_number := nextval('public.trial_account_number_seq'::regclass);
    candidate_email := lower('teste' || lpad(next_number::text, 3, '0') || '@trial.controlefinanceiro.app');

    exit when not exists (select 1 from public.allowed_emails a where a.email = candidate_email)
      and not exists (select 1 from public.app_profiles p where lower(p.email) = candidate_email)
      and not exists (select 1 from auth.users u where lower(u.email) = candidate_email);
  end loop;

  expires_at := now() + (greatest(coalesce(trial_minutes, 30), 1) * interval '1 minute');

  insert into public.allowed_emails (
    email,
    full_name,
    role,
    status,
    valid_until,
    valid_until_at,
    temp_password,
    temp_password_hash,
    must_change_password,
    is_trial,
    plan_type,
    purchase_platform,
    subscription_started_at,
    subscription_updated_at,
    account_created_at,
    claimed_at,
    created_by,
    updated_at
  )
  values (
    candidate_email,
    cleaned_name,
    'user',
    'active',
    expires_at::date,
    expires_at,
    null,
    crypt(temp_password_value, gen_salt('bf')),
    false,
    true,
    'trial',
    'manual',
    now(),
    now(),
    now(),
    null,
    auth.uid(),
    now()
  );

  return query
  select
    a.email,
    a.full_name,
    a.role,
    a.status,
    coalesce(a.plan_type, 'trial') as plan_type,
    a.valid_until,
    a.valid_until_at,
    coalesce(a.is_trial, true) as is_trial,
    temp_password_value::text as temp_password
  from public.allowed_emails a
  where a.email = candidate_email;
end;
$$;

create or replace function public.admin_list_accesses()
returns table (
  email text,
  full_name text,
  role text,
  status text,
  valid_until date,
  valid_until_at timestamptz,
  must_change_password boolean,
  is_trial boolean,
  plan_type text,
  purchase_platform text,
  purchase_reference text,
  subscription_started_at timestamptz,
  subscription_updated_at timestamptz,
  account_created_at timestamptz,
  claimed_at timestamptz,
  created_by uuid,
  created_at timestamptz,
  updated_at timestamptz,
  profile_user_id uuid,
  profile_full_name text,
  profile_last_login_at timestamptz
)
language plpgsql
security definer
set search_path = public, extensions
stable
as $$
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Sua sessao nao tem permissao de administrador ativa no Supabase.';
  end if;

  return query
  select
    a.email,
    a.full_name,
    a.role,
    a.status,
    a.valid_until,
    a.valid_until_at,
    coalesce(a.must_change_password, false) as must_change_password,
    coalesce(a.is_trial, false) as is_trial,
    coalesce(a.plan_type, 'manual') as plan_type,
    a.purchase_platform,
    a.purchase_reference,
    a.subscription_started_at,
    a.subscription_updated_at,
    a.account_created_at,
    a.claimed_at,
    a.created_by,
    a.created_at,
    a.updated_at,
    p.user_id as profile_user_id,
    p.full_name as profile_full_name,
    p.last_login_at as profile_last_login_at
  from public.allowed_emails a
  left join public.app_profiles p on lower(p.email) = a.email
  order by a.created_at desc
  limit 500;
end;
$$;

create or replace function public.admin_apply_access_plan(
  target_email text,
  selected_plan text,
  selected_platform text default null,
  selected_reference text default null
)
returns table (
  email text,
  plan_type text,
  valid_until date,
  valid_until_at timestamptz,
  status text
)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  normalized_email text;
  normalized_plan text;
  base_date timestamptz;
  expires_at timestamptz;
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Somente administradores podem aplicar planos.';
  end if;

  normalized_email := lower(trim(coalesce(target_email, '')));
  normalized_plan := public.normalize_plan_type(selected_plan);

  if normalized_email = '' then
    raise exception 'E-mail invalido.';
  end if;

  if normalized_plan not in ('trial', 'monthly', 'semiannual', 'annual') then
    raise exception 'Plano invalido.';
  end if;

  select greatest(coalesce(a.valid_until_at, now()), now())
    into base_date
  from public.allowed_emails a
  where a.email = normalized_email;

  base_date := coalesce(base_date, now());
  expires_at := public.get_plan_expiry(base_date, normalized_plan);

  update public.allowed_emails
     set plan_type = normalized_plan,
         purchase_platform = nullif(trim(coalesce(selected_platform, '')), ''),
         purchase_reference = nullif(trim(coalesce(selected_reference, '')), ''),
         subscription_started_at = coalesce(subscription_started_at, now()),
         subscription_updated_at = now(),
         valid_until = expires_at::date,
         valid_until_at = expires_at,
         status = 'active',
         updated_at = now()
   where public.allowed_emails.email = normalized_email;

  if not found then
    raise exception 'Acesso nao encontrado para este e-mail.';
  end if;

  update public.app_profiles
     set plan_type = normalized_plan,
         purchase_platform = nullif(trim(coalesce(selected_platform, '')), ''),
         purchase_reference = nullif(trim(coalesce(selected_reference, '')), ''),
         subscription_started_at = coalesce(subscription_started_at, now()),
         subscription_updated_at = now(),
         valid_until = expires_at::date,
         valid_until_at = expires_at,
         status = 'active',
         updated_at = now()
   where public.app_profiles.email = normalized_email;

  return query
  select
    a.email,
    a.plan_type,
    a.valid_until,
    a.valid_until_at,
    a.status
  from public.allowed_emails a
  where a.email = normalized_email;
end;
$$;

create or replace function public.admin_set_auth_ban(target_email text, should_ban boolean)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  normalized_email text;
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Somente administradores podem alterar bloqueio de autenticacao.';
  end if;

  normalized_email := lower(trim(coalesce(target_email, '')));
  if normalized_email = '' then
    raise exception 'E-mail invalido.';
  end if;

  if normalized_email = lower(coalesce(auth.jwt() ->> 'email', '')) then
    raise exception 'Nao altere a autenticacao da propria conta administradora por aqui.';
  end if;

  update auth.users
     set banned_until = case when should_ban then '9999-12-31 23:59:59+00'::timestamptz else null end,
         updated_at = now()
   where lower(email) = normalized_email;

  return true;
end;
$$;

create or replace function public.admin_delete_access_account(
  target_email text,
  deletion_reason text default null
)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  normalized_email text;
  target_user_id uuid;
  cleaned_reason text;
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Somente administradores podem excluir acessos.';
  end if;

  normalized_email := lower(trim(coalesce(target_email, '')));
  cleaned_reason := left(trim(coalesce(deletion_reason, '')), 240);

  if normalized_email = '' then
    raise exception 'E-mail invalido.';
  end if;

  if cleaned_reason = '' or length(cleaned_reason) < 8 then
    raise exception 'Informe o motivo da exclusao com pelo menos 8 caracteres.';
  end if;

  if normalized_email = lower(coalesce(auth.jwt() ->> 'email', '')) then
    raise exception 'Nao exclua a propria conta administradora por aqui.';
  end if;

  insert into public.access_deletion_notices (
    email,
    reason,
    deleted_by,
    deleted_at
  )
  values (
    normalized_email,
    cleaned_reason,
    auth.uid(),
    now()
  )
  on conflict (email) do update
     set reason = excluded.reason,
         deleted_by = excluded.deleted_by,
         deleted_at = excluded.deleted_at;

  select u.id
    into target_user_id
  from auth.users u
  where lower(u.email) = normalized_email
  limit 1;

  if target_user_id is not null then
    delete from public.user_states s where s.user_id = target_user_id;
    delete from public.app_profiles p where p.user_id = target_user_id;
    delete from auth.users u where u.id = target_user_id;
  end if;

  delete from public.app_profiles p where lower(p.email) = normalized_email;
  delete from public.allowed_emails a where a.email = normalized_email;

  return true;
end;
$$;

create or replace function public.clear_access_deletion_notice_on_allow()
returns trigger
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  if new.status = 'active' then
    delete from public.access_deletion_notices n
     where n.email = lower(trim(new.email));
  end if;
  return new;
end;
$$;

drop trigger if exists trg_clear_access_deletion_notice_on_allow on public.allowed_emails;
create trigger trg_clear_access_deletion_notice_on_allow
after insert or update of status on public.allowed_emails
for each row
execute function public.clear_access_deletion_notice_on_allow();

create or replace function public.sync_profile_from_allowed_email()
returns trigger
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  access_row public.allowed_emails%rowtype;
begin
  new.email := lower(trim(new.email));

  select *
    into access_row
  from public.allowed_emails a
  where a.email = new.email;

  if access_row.email is null then
    raise exception 'Email nao autorizado para uso.';
  end if;

  new.role := access_row.role;
  new.status := access_row.status;
  new.valid_until := access_row.valid_until;
  new.valid_until_at := access_row.valid_until_at;
  new.is_trial := coalesce(access_row.is_trial, false);
  new.plan_type := coalesce(access_row.plan_type, 'manual');
  new.purchase_platform := access_row.purchase_platform;
  new.purchase_reference := access_row.purchase_reference;
  new.subscription_started_at := access_row.subscription_started_at;
  new.subscription_updated_at := access_row.subscription_updated_at;
  new.full_name := coalesce(nullif(access_row.full_name, ''), nullif(new.full_name, ''), new.email);
  new.updated_at := now();

  return new;
end;
$$;

drop trigger if exists trg_sync_profile_from_allowed_email on public.app_profiles;
create trigger trg_sync_profile_from_allowed_email
before insert or update on public.app_profiles
for each row
execute function public.sync_profile_from_allowed_email();

create or replace function public.sync_allowed_email_to_profiles()
returns trigger
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  update public.app_profiles p
     set full_name = coalesce(nullif(new.full_name, ''), p.full_name),
         role = new.role,
         status = new.status,
         valid_until = new.valid_until,
         valid_until_at = new.valid_until_at,
         is_trial = coalesce(new.is_trial, false),
         plan_type = coalesce(new.plan_type, p.plan_type, 'manual'),
         purchase_platform = new.purchase_platform,
         purchase_reference = new.purchase_reference,
         subscription_started_at = new.subscription_started_at,
         subscription_updated_at = new.subscription_updated_at,
         updated_at = now()
   where lower(p.email) = lower(new.email);

  return new;
end;
$$;

drop trigger if exists trg_sync_allowed_email_to_profiles on public.allowed_emails;
create trigger trg_sync_allowed_email_to_profiles
after insert or update on public.allowed_emails
for each row
execute function public.sync_allowed_email_to_profiles();

create or replace function public.mark_password_changed()
returns void
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  current_email text;
begin
  current_email := lower(coalesce(auth.jwt() ->> 'email', ''));

  if current_email = '' then
    raise exception 'Usuario autenticado nao encontrado.';
  end if;

  update public.allowed_emails
     set must_change_password = false,
         temp_password = null,
         temp_password_hash = null,
         claimed_at = coalesce(claimed_at, now()),
         updated_at = now()
   where public.allowed_emails.email = current_email;

  if not found then
    raise exception 'Acesso administrado nao encontrado para este e-mail.';
  end if;

  update public.app_profiles
     set last_login_at = now(),
         updated_at = now()
   where public.app_profiles.email = current_email;
end;
$$;

drop policy if exists "Users can read own state" on public.user_states;
drop policy if exists "Users can insert own state" on public.user_states;
drop policy if exists "Users can update own state" on public.user_states;
drop policy if exists "Users read own state or admins read all" on public.user_states;
drop policy if exists "Users insert own state or admins insert all" on public.user_states;
drop policy if exists "Users update own state or admins update all" on public.user_states;
drop policy if exists "Users delete own state or admins delete all" on public.user_states;
drop policy if exists "states select" on public.user_states;
drop policy if exists "states insert" on public.user_states;
drop policy if exists "states update" on public.user_states;
drop policy if exists "states delete" on public.user_states;

drop policy if exists "Admins can read allowed emails" on public.allowed_emails;
drop policy if exists "Admins can insert allowed emails" on public.allowed_emails;
drop policy if exists "Admins can update allowed emails" on public.allowed_emails;
drop policy if exists "Admins can delete allowed emails" on public.allowed_emails;
drop policy if exists "allowed select" on public.allowed_emails;
drop policy if exists "allowed insert" on public.allowed_emails;
drop policy if exists "allowed update" on public.allowed_emails;
drop policy if exists "allowed delete" on public.allowed_emails;

drop policy if exists "Users and admins can read profiles" on public.app_profiles;
drop policy if exists "Users bootstrap or create own profile" on public.app_profiles;
drop policy if exists "Users update own profile and admins manage all" on public.app_profiles;
drop policy if exists "Admins can delete profiles" on public.app_profiles;
drop policy if exists "profiles select" on public.app_profiles;
drop policy if exists "profiles insert" on public.app_profiles;
drop policy if exists "profiles update" on public.app_profiles;
drop policy if exists "profiles delete" on public.app_profiles;

create policy "allowed select"
on public.allowed_emails
for select
to authenticated
using (
  public.is_admin(auth.uid())
  or email = lower(coalesce(auth.jwt() ->> 'email', ''))
);

create policy "allowed insert"
on public.allowed_emails
for insert
to authenticated
with check (
  public.is_admin(auth.uid())
  or (
    not public.has_any_admin()
    and role = 'admin'
    and email = lower(coalesce(auth.jwt() ->> 'email', ''))
  )
);

create policy "allowed update"
on public.allowed_emails
for update
to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

create policy "allowed delete"
on public.allowed_emails
for delete
to authenticated
using (public.is_admin(auth.uid()));

create policy "profiles select"
on public.app_profiles
for select
to authenticated
using (
  public.is_admin(auth.uid())
  or user_id = auth.uid()
);

create policy "profiles insert"
on public.app_profiles
for insert
to authenticated
with check (
  user_id = auth.uid()
  and email = lower(coalesce(auth.jwt() ->> 'email', ''))
  and (
    public.has_active_access(lower(coalesce(auth.jwt() ->> 'email', '')))
    or (
      not public.has_any_admin()
      and role = 'admin'
    )
  )
);

create policy "profiles update"
on public.app_profiles
for update
to authenticated
using (
  public.is_admin(auth.uid())
  or user_id = auth.uid()
)
with check (
  public.is_admin(auth.uid())
  or (
    user_id = auth.uid()
    and email = lower(coalesce(auth.jwt() ->> 'email', ''))
    and public.has_active_access(lower(coalesce(auth.jwt() ->> 'email', '')))
  )
);

create policy "profiles delete"
on public.app_profiles
for delete
to authenticated
using (public.is_admin(auth.uid()));

create policy "states select"
on public.user_states
for select
to authenticated
using (
  public.is_admin(auth.uid())
  or (
    auth.uid() = user_id
    and public.has_active_access(lower(coalesce(auth.jwt() ->> 'email', '')))
  )
);

create policy "states insert"
on public.user_states
for insert
to authenticated
with check (
  public.is_admin(auth.uid())
  or (
    auth.uid() = user_id
    and public.has_active_access(lower(coalesce(auth.jwt() ->> 'email', '')))
  )
);

create policy "states update"
on public.user_states
for update
to authenticated
using (
  public.is_admin(auth.uid())
  or (
    auth.uid() = user_id
    and public.has_active_access(lower(coalesce(auth.jwt() ->> 'email', '')))
  )
)
with check (
  public.is_admin(auth.uid())
  or (
    auth.uid() = user_id
    and public.has_active_access(lower(coalesce(auth.jwt() ->> 'email', '')))
  )
);

create policy "states delete"
on public.user_states
for delete
to authenticated
using (
  public.is_admin(auth.uid())
  or auth.uid() = user_id
);

revoke all on function public.normalize_plan_type(text) from public;
revoke all on function public.get_plan_expiry(timestamptz, text) from public;
revoke all on function public.is_admin(uuid) from public;
revoke all on function public.has_active_access(text) from public;
revoke all on function public.has_any_admin() from public;
revoke all on function public.hash_allowed_email_temp_password() from public;
revoke all on function public.can_start_first_access(text, text) from public;
revoke all on function public.get_my_access_status() from public;
revoke all on function public.next_trial_email() from public;
revoke all on function public.admin_create_managed_access(text, text, text, text, timestamptz, text, text, text) from public;
revoke all on function public.admin_create_trial_access(text, text, integer) from public;
revoke all on function public.admin_list_accesses() from public;
revoke all on function public.admin_apply_access_plan(text, text, text, text) from public;
revoke all on function public.admin_set_auth_ban(text, boolean) from public;
revoke all on function public.admin_delete_access_account(text, text) from public;
revoke all on function public.get_access_deletion_notice(text) from public;
revoke all on function public.clear_access_deletion_notice_on_allow() from public;
revoke all on function public.admin_register_audit(text, text, text, text) from public;
revoke all on function public.admin_list_audit_logs(integer) from public;
revoke all on function public.sync_profile_from_allowed_email() from public;
revoke all on function public.sync_allowed_email_to_profiles() from public;
revoke all on function public.mark_password_changed() from public;

grant execute on function public.is_admin(uuid) to authenticated;
grant execute on function public.has_active_access(text) to authenticated;
grant execute on function public.has_any_admin() to authenticated;
grant execute on function public.can_start_first_access(text, text) to anon, authenticated;
grant execute on function public.get_access_deletion_notice(text) to anon, authenticated;
grant execute on function public.get_my_access_status() to authenticated;
grant execute on function public.next_trial_email() to authenticated;
grant execute on function public.admin_create_managed_access(text, text, text, text, timestamptz, text, text, text) to authenticated;
grant execute on function public.admin_create_trial_access(text, text, integer) to authenticated;
grant execute on function public.admin_list_accesses() to authenticated;
grant execute on function public.admin_apply_access_plan(text, text, text, text) to authenticated;
grant execute on function public.admin_set_auth_ban(text, boolean) to authenticated;
grant execute on function public.admin_delete_access_account(text, text) to authenticated;
grant execute on function public.admin_register_audit(text, text, text, text) to authenticated;
grant execute on function public.admin_list_audit_logs(integer) to authenticated;
grant execute on function public.mark_password_changed() to authenticated;
